# Generated by Django 4.0.4 on 2022-05-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emailid',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
